import React, { useState, useEffect ,useContext} from "react";
import { useNavigate } from "react-router-dom";
import axios from "../config/axios";
import { MdArrowForward } from "react-icons/md";
import { IoIosLogOut } from "react-icons/io";

const Home = () => {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState("server");
  const [displayedText, setDisplayedText] = useState("");
  const [user, setUser] = useState(null);
  const [isTyping, setIsTyping] = useState(false);
  const [loading, setLoading] = useState(true);
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });



  const codeSnippets = {
    server: `// server.js - Generated by @ai\nconst express = require('express');\nconst app = express();\n\napp.use(express.json());\n\napp.get('/api/status', (req, res) => {\n  res.json({ status: 'AI Agent Active' });\n});\n\napp.listen(3000, () => console.log('Server online'));`,
    schema: `// models/User.js - Generated by @ai\nconst { DataTypes } = require('sequelize');\nconst db = require('../config/database');\n\nconst User = db.define('User', {\n  email: {\n    type: DataTypes.STRING,\n    allowNull: false,\n    unique: true\n  },\n  password: {\n    type: DataTypes.STRING,\n    allowNull: false\n  }\n});\n\nmodule.exports = User;`,
  };

  // Track mouse position for parallax effect
  useEffect(() => {
    const handleMouseMove = (e) => {
      setMousePosition({ x: e.clientX, y: e.clientY });
    };

    window.addEventListener("mousemove", handleMouseMove);
    return () => window.removeEventListener("mousemove", handleMouseMove);
  }, []);

  // Simulate AI typing effect when switching tabs
  useEffect(() => {
    setIsTyping(true);
    setDisplayedText("");
    let index = 0;
    const targetText = codeSnippets[activeTab];

    const interval = setInterval(() => {
      if (index < targetText.length) {
        setDisplayedText((prev) => prev + targetText.charAt(index));
        index++;
      } else {
        setIsTyping(false);
        clearInterval(interval);
      }
    }, 8);

    return () => clearInterval(interval);
  }, [activeTab]);

  // Fetch user profile with proper error handling
  useEffect(() => {
    const getProfile = async () => {
      try {
        setLoading(true);
        const res = await axios.get("/users/profile");
        if (res.data && res.data.user) {
          setUser(res.data.user);
        } else {
          setUser(null);
        }
      } catch (error) {
        console.error("Auth check failed:", error);
        setUser(null);
      } finally {
        setLoading(false);
      }
    };

    getProfile();
  }, []);

  // Parallax offset calculation
  const parallaxOffset = {
    x: mousePosition.x * 0.02,
    y: mousePosition.y * 0.02,
  };

  // Handle logout
  const handleLogout = async () => {
    try {
      await axios.post("/users/logout");
      setUser(null);
      navigate("/");
    } catch (error) {
      setUser(null);
      navigate("/");
    }
  };

  // Function to mask email
  const maskEmail = (email) => {
    if (!email) return "";
    const [localPart, domain] = email.split("@");
    const visibleChars = Math.max(2, Math.ceil(localPart.length / 3));
    const masked = localPart.substring(0, visibleChars) + "***";
    return `${masked}@${domain}`;
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 font-sans selection:bg-indigo-500/30 overflow-x-hidden relative">
      {/* Animated background gradient */}
      <div className="fixed inset-0 -z-50">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-slate-900/60 via-slate-950 to-slate-950" />
        <div
          className="absolute top-0 left-1/4 w-96 h-96 bg-indigo-500/10 rounded-full blur-3xl animate-pulse"
          style={{ animation: "float 8s ease-in-out infinite" }}
        />
        <div
          className="absolute bottom-0 right-1/4 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl animate-pulse"
          style={{ animation: "float 10s ease-in-out infinite 2s" }}
        />
      </div>

      {/* 1. FIXED GLASS NAVBAR */}
      <nav className="fixed top-0 left-0 right-0 z-50 border-b border-slate-800/40 bg-slate-950/60 backdrop-blur-xl animate-fadeIn">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="flex h-16 items-center justify-between">
            {/* Logo */}
            <div
              className="flex items-center space-x-2 cursor-pointer group"
              onClick={() => navigate("/")}>
              <div className="h-7 w-7 rounded-lg overflow-hidden shadow-lg shadow-indigo-500/20 group-hover:shadow-indigo-500/40 transition-all duration-300 group-hover:scale-110">
                <img
                  src="/favlogo.png"
                  alt="Logo"
                  className="h-full w-full object-cover"
                />
              </div>
              <span className="text-lg font-medium tracking-tight text-slate-200 group-hover:text-slate-100 transition-colors">
                Dev<span className="text-indigo-400 font-semibold">Thread</span>
              </span>
            </div>

            {/* Auth Actions */}
            <div className="flex items-center gap-4">
              {loading ? (
                <div className="h-10 w-20 bg-slate-800/30 rounded-lg animate-pulse" />
              ) : user ? (
                <>
                  <button
                    onClick={() => navigate("/dashboard")}
                    className="rounded-xl bg-gradient-to-r from-indigo-600 to-indigo-500 px-4 py-2 text-sm font-medium text-white shadow-md shadow-indigo-600/30 transition-all hover:shadow-lg hover:shadow-indigo-600/40 hover:scale-105 transform">
                    Dashboard
                  </button>

                  <div className="rounded-xl border border-slate-800/60 bg-slate-900/40 px-4 py-2 text-sm text-slate-300 backdrop-blur-sm">
                    {maskEmail(user.email)}
                  </div>

                  <button
                    onClick={handleLogout}
                    className="rounded-xl border border-slate-700 bg-slate-900/40 px-4 py-2 text-sm font-medium text-slate-300 transition-all hover:text-red-300 hover:border-red-500/40 hover:bg-slate-900/60 hover:scale-105 transform backdrop-blur-sm">
                    <IoIosLogOut size={20}/>
                  </button>
                </>
              ) : (
                <>
                  <button
                    onClick={() => navigate("/login")}
                    className="text-sm font-medium text-slate-400 transition-all hover:text-slate-200 hover:scale-105 transform duration-200">
                    Login
                  </button>

                  <button
                    onClick={() => navigate("/register")}
                    className="rounded-xl bg-gradient-to-r from-indigo-600 to-indigo-500 px-4 py-2 text-sm font-medium text-white shadow-md shadow-indigo-600/30 transition-all hover:shadow-lg hover:shadow-indigo-600/40 hover:scale-105 transform">
                    Register
                  </button>
                </>
              )}
            </div>
          </div>
        </div>
      </nav>

      {/* 2. HERO SECTION */}
      <header className="relative mx-auto max-w-5xl px-4 pt-32 pb-16 text-center sm:px-6 lg:px-8">
        <div className="space-y-6 animate-slideInDown">
          {/* Badge with animation */}
          <div className="inline-flex items-center gap-2 rounded-full border border-indigo-500/30 bg-indigo-500/10 px-4 py-2 text-xs font-medium text-indigo-300 backdrop-blur-sm hover:border-indigo-500/60 hover:bg-indigo-500/15 transition-all duration-300 cursor-pointer group">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-indigo-400 opacity-75" />
              <span className="relative inline-flex rounded-full h-2 w-2 bg-indigo-500" />
            </span>
            <span>Now Live: Gemini AI Contextual Engine</span>
          </div>

          {/* Main headline with 3D effect */}
          <div className="relative">
            <h1 className="text-5xl md:text-7xl font-bold tracking-tighter text-slate-100 leading-tight max-w-4xl mx-auto animate-slideInDown [animation-delay:0.2s]">
              Your production MERN app builds with{" "}
              <span className="relative inline-block">
                <span className="absolute inset-0 bg-gradient-to-r from-indigo-400 via-purple-400 to-pink-400 blur-xl opacity-50 animate-pulse" />
                <span className="relative text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 via-purple-400 to-pink-400 animate-gradient">
                  an AI Agent
                </span>
              </span>
            </h1>
          </div>

          {/* Description */}
          <p className="mx-auto max-w-2xl text-base md:text-lg text-slate-400 leading-relaxed animate-slideInUp [animation-delay:0.4s]">
            A collaborative workspace environment. Manage complex real-time
            projects, chat instantly, and direct your integrated software
            container using simple{" "}
            <code className="rounded-lg bg-slate-900/60 border border-slate-700 px-2 py-1 text-indigo-300 font-mono text-sm backdrop-blur-sm hover:border-indigo-500/40 transition-all">
              @ai
            </code>{" "}
            syntax commands.
          </p>

          {/* CTA Buttons */}
          <div className="pt-6 flex flex-col sm:flex-row items-center justify-center gap-4 animate-slideInUp [animation-delay:0.6s]">
            <button
              onClick={() => navigate("/register")}
              className="w-full sm:w-auto relative group rounded-xl overflow-hidden">
              <div className="absolute inset-0 bg-gradient-to-r from-indigo-600 to-purple-600 opacity-100 group-hover:opacity-0 transition-opacity duration-300" />
              <div className="absolute inset-0 bg-gradient-to-r from-purple-600 to-pink-600 opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
              <span className="relative px-8 py-3.5 font-semibold text-white flex items-center justify-center gap-2 group-hover:scale-105 transform transition-transform">
                Start Building Now
                <MdArrowForward className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </span>
            </button>
            <button
              onClick={() => navigate("/login")}
              className="w-full sm:w-auto rounded-xl bg-slate-900/40 border border-slate-700 hover:border-indigo-500/40 px-8 py-3.5 font-semibold text-slate-300 transition-all hover:text-indigo-300 hover:bg-slate-900/60 hover:scale-105 transform backdrop-blur-sm">
              Open Dashboard
            </button>
          </div>
        </div>
      </header>

      {/* 3. TECH STACK BADGES */}
      <section className="mx-auto max-w-4xl px-4 py-12 border-y border-slate-800/50 text-center backdrop-blur-sm">
        <p className="text-xs uppercase tracking-widest text-slate-500 mb-8 font-bold">
          Powering Your Pipeline
        </p>
        <div className="flex flex-wrap items-center justify-center gap-6 sm:gap-12">
          {["REACT", "NODE.JS", "MONGODB", "EXPRESS", "GEMINI PRO AI"].map(
            (tech, idx) => (
              <div
                key={tech}
                className="group relative cursor-default animate-slideInUp"
                style={{ animationDelay: `${idx * 0.1}s` }}>
                <div className="absolute -inset-3 bg-gradient-to-r from-indigo-500/20 to-purple-500/20 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity duration-300 blur-lg" />
                <span className="relative text-sm font-bold tracking-wider font-mono text-slate-300 group-hover:text-indigo-300 transition-colors">
                  {tech}
                </span>
              </div>
            ),
          )}
        </div>
      </section>

      {/* 4. INTERACTIVE PLAYGROUND */}
      <section className="mx-auto max-w-5xl px-4 py-20 sm:px-6 lg:px-8 animate-slideInUp">
        <div className="rounded-2xl border border-slate-800/60 bg-slate-900/30 p-2 shadow-2xl backdrop-blur-md hover:shadow-indigo-500/20 transition-shadow duration-500 perspective">
          {/* Mock Browser Header */}
          <div className="flex items-center justify-between px-4 py-3 border-b border-slate-800/60 bg-slate-950/50 rounded-t-xl backdrop-blur-sm">
            <div className="flex items-center space-x-2">
              <div className="h-3 w-3 rounded-full bg-rose-500/70 hover:bg-rose-500 transition-colors shadow-lg shadow-rose-500/20" />
              <div className="h-3 w-3 rounded-full bg-amber-500/70 hover:bg-amber-500 transition-colors shadow-lg shadow-amber-500/20" />
              <div className="h-3 w-3 rounded-full bg-emerald-500/70 hover:bg-emerald-500 transition-colors shadow-lg shadow-emerald-500/20" />
              <span className="text-xs font-mono text-slate-500 pl-4">
                workspace-sandbox://agent-shell
              </span>
            </div>
            {isTyping && (
              <div className="flex items-center space-x-1.5 animate-pulse">
                <span className="h-2 w-2 rounded-full bg-indigo-400 shadow-lg shadow-indigo-400/50 animate-bounce" />
                <span className="text-[11px] font-mono text-indigo-400">
                  Agent writing code...
                </span>
              </div>
            )}
          </div>

          {/* Sandbox Layout Workspace */}
          <div className="grid grid-cols-1 md:grid-cols-3 min-h-[400px] font-mono text-sm bg-slate-950/90 rounded-b-xl overflow-hidden">
            {/* Prompt Selector Sidebar */}
            <div className="p-4 border-r border-slate-800/40 bg-slate-900/20 space-y-3">
              <div className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-3">
                Select Prompt
              </div>

              {["server", "schema"].map((tab, idx) => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`w-full text-left p-3 rounded-xl border transition-all text-xs transform duration-200 hover:scale-105 animate-slideInDown`}
                  style={{ animationDelay: `${idx * 0.1}s` }}
                  style={{
                    background:
                      activeTab === tab
                        ? "rgba(99, 102, 241, 0.1)"
                        : "transparent",
                    borderColor:
                      activeTab === tab
                        ? "rgba(99, 102, 241, 0.4)"
                        : "rgb(15, 23, 42)",
                    color:
                      activeTab === tab
                        ? "rgb(165, 180, 252)"
                        : "rgb(148, 163, 184)",
                  }}>
                  <span className="text-indigo-400 font-bold block mb-1">
                    @ai
                  </span>
                  {tab === "server"
                    ? "Create a secure express server"
                    : "Define a user database schema"}
                </button>
              ))}
            </div>

            {/* Simulated Live Output Stream */}
            <div className="col-span-2 p-6 bg-slate-950/70 overflow-y-auto text-slate-300 max-h-[400px] whitespace-pre-wrap leading-relaxed select-none">
              <span className="text-indigo-400/70">~/agent-shell $</span>{" "}
              {displayedText}
              <span
                className="inline-block w-2 h-5 ml-1 bg-indigo-400 shadow-lg shadow-indigo-400/50"
                style={{ animation: "blink 1s step-end infinite" }}
              />
            </div>
          </div>
        </div>
      </section>

      {/* 5. MODERN BENTO FEATURES GRID */}
      <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:px-8">
        <div className="text-center max-w-2xl mx-auto mb-16 animate-slideInUp">
          <h2 className="text-4xl md:text-5xl font-bold tracking-tight text-slate-200 mb-4">
            Engineered for agile execution
          </h2>
          <p className="text-base text-slate-400 leading-relaxed">
            Everything you need to turn abstract structural concepts into
            working codebases instantly.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {/* Big Item 1 */}
          <FeatureCard
            span="md:col-span-2"
            number="01"
            color="indigo"
            title="Shared Multi-User Workspace Rooms"
            description="Coordinate dynamically with structural team rooms. Stream chat data instantly over system sockets to maintain consistent implementation direction."
            tech="WebSockets + Realtime Streams"
            delay="0s"
          />

          {/* Small Item 2 */}
          <FeatureCard
            number="02"
            color="purple"
            title="Context-Aware AI Container"
            description="The Gemini parser reads your current file tree configuration, generating logical additions without breaking existing files."
            tech="Structural Generation"
            delay="0.1s"
          />

          {/* Small Item 3 */}
          <FeatureCard
            number="03"
            color="pink"
            title="Dual Relational Control"
            description="Supports isolated schemas seamlessly. Instruct the workspace to construct elements using flexible MongoDB models or structured SQL tables."
            tech="Sequelize & NoSQL Compatible"
            delay="0.2s"
          />

          {/* Big Item 4 */}
          <FeatureCard
            span="md:col-span-2"
            number="04"
            color="emerald"
            title="Persistent System File Tracking"
            description="Never lose progress across server restarts. Every generation variant, user message, and virtual sandbox file update saves continuously back to the cloud database layer."
            tech="Automated Cloud State Backups"
            delay="0.3s"
          />
        </div>
      </section>

      {/* FOOTER */}
      <footer className="mt-20 border-t border-slate-900/50 py-8 text-center text-xs text-slate-500 font-mono backdrop-blur-sm animate-fadeIn">
        &copy; {new Date().getFullYear()} Dev Thread Systems Inc. All project
        code sandboxes open-sourced.
      </footer>

      {/* Styles */}
      <style>{`
        @keyframes blink {
          50% { opacity: 0.5; }
        }

        @keyframes float {
          0%, 100% { transform: translateY(0px); }
          50% { transform: translateY(-20px); }
        }

        @keyframes slideInDown {
          from {
            opacity: 0;
            transform: translateY(-20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        @keyframes slideInUp {
          from {
            opacity: 0;
            transform: translateY(20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        @keyframes fadeIn {
          from { opacity: 0; }
          to { opacity: 1; }
        }

        @keyframes gradient {
          0%, 100% { background-position: 0% 50%; }
          50% { background-position: 100% 50%; }
        }

        .animate-slideInDown {
          animation: slideInDown 0.8s ease-out forwards;
          opacity: 0;
        }

        .animate-slideInUp {
          animation: slideInUp 0.8s ease-out forwards;
          opacity: 0;
        }

        .animate-fadeIn {
          animation: fadeIn 1s ease-out;
        }

        .animate-gradient {
          background-size: 200% 200%;
          animation: gradient 3s ease infinite;
        }

        .perspective {
          perspective: 1000px;
        }

        [animation-delay] {
          animation-delay: var(--animation-delay, 0s);
        }

        @media (prefers-reduced-motion: reduce) {
          * {
            animation-duration: 0.01ms !important;
            animation-iteration-count: 1 !important;
            transition-duration: 0.01ms !important;
          }
        }
      `}</style>
    </div>
  );
};

// Reusable Feature Card Component with 3D effect
const FeatureCard = ({
  span = "",
  number,
  color,
  title,
  description,
  tech,
  delay,
}) => {
  const [rotateX, setRotateX] = React.useState(0);
  const [rotateY, setRotateY] = React.useState(0);

  const handleMouseMove = (e) => {
    const card = e.currentTarget;
    const rect = card.getBoundingClientRect();
    const centerX = rect.width / 2;
    const centerY = rect.height / 2;
    const mouseX = e.clientX - rect.left;
    const mouseY = e.clientY - rect.top;

    const rotateXVal = (mouseY - centerY) / 10;
    const rotateYVal = (centerX - mouseX) / 10;

    setRotateX(rotateXVal);
    setRotateY(rotateYVal);
  };

  const handleMouseLeave = () => {
    setRotateX(0);
    setRotateY(0);
  };

  const colorMap = {
    indigo: {
      bg: "indigo-500/10",
      border: "indigo-500/20",
      text: "indigo-400",
      hover: "indigo-300",
    },
    purple: {
      bg: "purple-500/10",
      border: "purple-500/20",
      text: "purple-400",
      hover: "purple-300",
    },
    pink: {
      bg: "pink-500/10",
      border: "pink-500/20",
      text: "pink-400",
      hover: "pink-300",
    },
    emerald: {
      bg: "emerald-500/10",
      border: "emerald-500/20",
      text: "emerald-400",
      hover: "emerald-300",
    },
  };

  const colors = colorMap[color];

  return (
    <div
      className={`${span} animate-slideInUp`}
      style={{ "--animation-delay": delay }}>
      <div
        onMouseMove={handleMouseMove}
        onMouseLeave={handleMouseLeave}
        className={`group rounded-2xl border ${colors.border} bg-slate-900/20 p-8 hover:border-${color}-500/40 transition-all duration-300 backdrop-blur-sm flex flex-col justify-between ${span === "md:col-span-2" ? "min-h-[240px]" : ""} transform`}
        style={{
          transform: `perspective(1000px) rotateX(${rotateX}deg) rotateY(${rotateY}deg)`,
          boxShadow: `0 0 ${Math.abs(rotateX) + Math.abs(rotateY)}px ${colors.text}/20`,
        }}>
        <div>
          <div
            className={`h-10 w-10 rounded-lg bg-${color}-500/10 border border-${color}-500/20 flex items-center justify-center text-${color}-400 mb-4 font-bold text-sm group-hover:scale-110 transition-transform duration-300`}>
            {number}
          </div>
          <h3
            className={`text-xl font-semibold text-slate-200 group-hover:text-${colors.hover} transition-colors`}>
            {title}
          </h3>
          <p className="text-sm text-slate-400 mt-3 leading-relaxed">
            {description}
          </p>
        </div>
        <span className="text-xs font-mono text-slate-600 mt-6 group-hover:text-slate-500 transition-colors">
          {tech}
        </span>
      </div>
    </div>
  );
};

export default Home;
