import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";

const Home = () => {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState("server");
  const [displayedText, setDisplayedText] = useState("");
  const [isTyping, setIsTyping] = useState(false);

  const codeSnippets = {
    server: `// server.js - Generated by @ai\nconst express = require('express');\nconst app = express();\n\napp.use(express.json());\n\napp.get('/api/status', (req, res) => {\n  res.json({ status: 'AI Agent Active' });\n});\n\napp.listen(3000, () => console.log('Server online'));`,
    schema: `// models/User.js - Generated by @ai\nconst { DataTypes } = require('sequelize');\nconst db = require('../config/database');\n\nconst User = db.define('User', {\n  email: {\n    type: DataTypes.STRING,\n    allowNull: false,\n    unique: true\n  },\n  password: {\n    type: DataTypes.STRING,\n    allowNull: false\n  }\n});\n\nmodule.exports = User;`,
  };

  // Simulate AI typing effect when switching tabs
  useEffect(() => {
    setIsTyping(true);
    setDisplayedText("");
    let index = 0;
    const targetText = codeSnippets[activeTab];

    const interval = setInterval(() => {
      if (index < targetText.length) {
        setDisplayedText((prev) => prev + targetText.charAt(index));
        index++;
      } else {
        setIsTyping(false);
        clearInterval(interval);
      }
    }, 8);

    return () => clearInterval(interval);
  }, [activeTab]);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 font-sans selection:bg-indigo-500/30 overflow-x-hidden bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-slate-900/60 via-slate-950 to-slate-950">
      {/* 1. FIXED GLASS NAVBAR */}
      <nav className="fixed top-0 left-0 right-0 z-50 border-b border-slate-800/40 bg-slate-950/60 backdrop-blur-xl">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="flex h-16 items-center justify-between">
            {/* Logo */}
            <div
              className="flex items-center space-x-2 cursor-pointer"
              onClick={() => navigate("/")}>
              <div className="h-7 w-7 rounded-lg overflow-hidden shadow-lg shadow-indigo-500/20">
                <img
                  src="/favlogo.png"
                  alt="Logo"
                  className="h-full w-full object-cover"
                />
              </div>
              <span className="text-lg font-medium tracking-tight text-slate-200">
                Dev<span className="text-indigo-400 font-semibold">Thread</span>
              </span>
            </div>

            {/* Auth Actions */}
            <div className="flex items-center space-x-5">
              <button
                onClick={() => navigate("/login")}
                className="text-sm font-medium text-slate-400 transition-colors hover:text-slate-200 focus:outline-none">
                Login
              </button>
              <button
                onClick={() => navigate("/register")}
                className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-md shadow-indigo-600/20 transition-all duration-200 hover:bg-indigo-500 focus:outline-none">
                Register
              </button>
            </div>
          </div>
        </div>
      </nav>

      {/* 2. HERO SECTION */}
      <header className="relative mx-auto max-w-5xl px-4 pt-32 pb-16 text-center sm:px-6 lg:px-8">
        <div className="space-y-6">
          <div className="inline-flex items-center gap-2 rounded-full border border-indigo-500/20 bg-indigo-500/5 px-3 py-1 text-xs font-medium text-indigo-400 backdrop-blur-sm animate-pulse">
            <span>Now Live: Gemini AI Contextual Engine</span>
          </div>

          <h1 className="text-4xl font-bold tracking-tight text-slate-100 sm:text-6xl max-w-4xl mx-auto leading-none">
            Your production MERN app builds with{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 via-purple-400 to-pink-400">
              an AI Agent
            </span>
          </h1>

          <p className="mx-auto max-w-xl text-base text-slate-400 sm:text-lg">
            A collaborative workspace environment. Manage complex real-time
            projects, chat instantly, and direct your integrated software
            container using simple{" "}
            <code className="rounded bg-slate-900 border border-slate-800 px-1.5 py-0.5 text-indigo-300 font-mono text-sm">
              @ai
            </code>{" "}
            syntax commands.
          </p>

          <div className="pt-4 flex flex-col sm:flex-row items-center justify-center gap-4">
            <button
              onClick={() => navigate("/register")}
              className="w-full sm:w-auto rounded-xl bg-indigo-600 hover:bg-indigo-500 px-8 py-3.5 font-medium text-white shadow-lg shadow-indigo-600/20 transition-all focus:outline-none">
              Start Building Now
            </button>
            <button
              onClick={() => navigate("/login")}
              className="w-full sm:w-auto rounded-xl bg-slate-900/80 border border-slate-800 hover:border-slate-700 px-8 py-3.5 font-medium text-slate-300 transition-all focus:outline-none">
              Open Dashboard
            </button>
          </div>
        </div>
      </header>

      {/* 3. TECH STACK BADGES */}
      <section className="mx-auto max-w-4xl px-4 py-8 border-y border-slate-900 text-center">
        <p className="text-xs uppercase tracking-widest text-slate-500 mb-6 font-semibold">
          POWERING YOUR PIPELINE WITH SAAS CORE ARCHITECTURE
        </p>
        <div className="flex flex-wrap items-center justify-center gap-8 sm:gap-12 opacity-40 grayscale hover:grayscale-0 hover:opacity-80 transition-all duration-300">
          <span className="text-sm font-bold tracking-wider font-mono">
            REACT
          </span>
          <span className="text-sm font-bold tracking-wider font-mono">
            NODE.JS
          </span>
          <span className="text-sm font-bold tracking-wider font-mono">
            MONGODB
          </span>
          <span className="text-sm font-bold tracking-wider font-mono">
            SQL / SEQUELIZE
          </span>
          <span className="text-sm font-bold tracking-wider font-mono">
            GEMINI PRO AI
          </span>
        </div>
      </section>

      {/* 4. INTERACTIVE PLAYGROUND (THE LIVE PREVIEW) */}
      <section className="mx-auto max-w-5xl px-4 py-20 sm:px-6 lg:px-8">
        <div className="rounded-2xl border border-slate-800/80 bg-slate-900/20 p-2 shadow-2xl backdrop-blur-md">
          {/* Mock Browser Header */}
          <div className="flex items-center justify-between px-4 py-3 border-b border-slate-800/60 bg-slate-950/40 rounded-t-xl">
            <div className="flex items-center space-x-2">
              <div className="h-3 w-3 rounded-full bg-rose-500/70" />
              <div className="h-3 w-3 rounded-full bg-amber-500/70" />
              <div className="h-3 w-3 rounded-full bg-emerald-500/70" />
              <span className="text-xs font-mono text-slate-500 pl-4">
                workspace-sandbox://agent-shell
              </span>
            </div>
            {isTyping && (
              <div className="flex items-center space-x-1.5">
                <span className="h-2 w-2 rounded-full bg-indigo-400 animate-ping" />
                <span className="text-[11px] font-mono text-indigo-400">
                  Agent writing code...
                </span>
              </div>
            )}
          </div>

          {/* Sandbox Layout Workspace */}
          <div className="grid grid-cols-1 md:grid-cols-3 min-h-[380px] font-mono text-sm bg-slate-950/90 rounded-b-xl overflow-hidden">
            {/* Prompt Selector Sidebar */}
            <div className="p-4 border-r border-slate-800/40 bg-slate-900/10 space-y-3">
              <div className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">
                Select Prompt Instruction
              </div>

              <button
                onClick={() => setActiveTab("server")}
                className={`w-full text-left p-3 rounded-xl border transition-all text-xs ${activeTab === "server" ? "bg-indigo-600/10 border-indigo-500/40 text-indigo-300" : "bg-transparent border-slate-900 text-slate-400 hover:border-slate-800/60"}`}>
                <span className="text-indigo-400 font-bold block mb-1">
                  @ai
                </span>
                "Create a secure express server setup with status endpoints"
              </button>

              <button
                onClick={() => setActiveTab("schema")}
                className={`w-full text-left p-3 rounded-xl border transition-all text-xs ${activeTab === "schema" ? "bg-indigo-600/10 border-indigo-500/40 text-indigo-300" : "bg-transparent border-slate-900 text-slate-400 hover:border-slate-800/60"}`}>
                <span className="text-indigo-400 font-bold block mb-1">
                  @ai
                </span>
                "Define a relative Sequelize system user database schema"
              </button>
            </div>

            {/* Simulated Live Output Stream */}
            <div className="col-span-2 p-6 bg-slate-950 overflow-y-auto text-slate-300 max-h-[400px] whitespace-pre-wrap leading-relaxed select-none">
              {displayedText}
              <span
                className="inline-block w-2 h-4 ml-1 bg-indigo-400 animate-caret"
                style={{ animation: "blink 1s step-end infinite" }}
              />
            </div>
          </div>
        </div>
      </section>

      {/* 5. MODERN BENTO FEATURES GRID */}
      <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:px-8">
        <div className="text-center max-w-xl mx-auto mb-16">
          <h2 className="text-3xl font-semibold tracking-tight text-slate-200">
            Engineered for agile execution
          </h2>
          <p className="text-sm text-slate-400 mt-2">
            Everything you need to turn abstract structural concepts into
            working codebases instantly.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {/* Big Item 1: Real-time Context */}
          <div className="md:col-span-2 group rounded-2xl border border-slate-800/60 bg-slate-900/20 p-8 hover:border-indigo-500/20 transition-all duration-300 backdrop-blur-sm flex flex-col justify-between min-h-[240px]">
            <div>
              <div className="h-8 w-8 rounded-lg bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400 mb-4 font-bold text-sm">
                01
              </div>
              <h3 className="text-lg font-medium text-slate-200 group-hover:text-indigo-300 transition-colors">
                Shared Multi-User Workspace Rooms
              </h3>
              <p className="text-sm text-slate-400 mt-2 max-w-md">
                Coordinate dynamically with structural team rooms. Stream chat
                data instantly over system sockets to maintain consistent
                implementation direction.
              </p>
            </div>
            <span className="text-xs font-mono text-slate-600 mt-4">
              WebSockets + Realtime Streams
            </span>
          </div>

          {/* Small Item 2: Code Execution */}
          <div className="group rounded-2xl border border-slate-800/60 bg-slate-900/20 p-8 hover:border-indigo-500/20 transition-all duration-300 backdrop-blur-sm flex flex-col justify-between">
            <div>
              <div className="h-8 w-8 rounded-lg bg-purple-500/10 border border-purple-500/20 flex items-center justify-center text-purple-400 mb-4 font-bold text-sm">
                02
              </div>
              <h3 className="text-lg font-medium text-slate-200 group-hover:text-purple-300 transition-colors">
                Context-Aware AI Container
              </h3>
              <p className="text-sm text-slate-400 mt-2">
                The Gemini parser reads your current file tree configuration,
                generating logical additions without breaking existing files.
              </p>
            </div>
            <span className="text-xs font-mono text-slate-600 mt-4">
              Structural Generation
            </span>
          </div>

          {/* Small Item 3: Relational Support */}
          <div className="group rounded-2xl border border-slate-800/60 bg-slate-900/20 p-8 hover:border-indigo-500/20 transition-all duration-300 backdrop-blur-sm flex flex-col justify-between">
            <div>
              <div className="h-8 w-8 rounded-lg bg-pink-500/10 border border-pink-500/20 flex items-center justify-center text-pink-400 mb-4 font-bold text-sm">
                03
              </div>
              <h3 className="text-lg font-medium text-slate-200 group-hover:text-pink-300 transition-colors">
                Dual Relational Control
              </h3>
              <p className="text-sm text-slate-400 mt-2">
                Supports isolated schemas seamlessly. Instruct the workspace to
                construct elements using flexible MongoDB models or structured
                SQL tables.
              </p>
            </div>
            <span className="text-xs font-mono text-slate-600 mt-4">
              Sequelize & NoSQL Compatible
            </span>
          </div>

          {/* Big Item 4: Instant Code Sandbox */}
          <div className="md:col-span-2 group rounded-2xl border border-slate-800/60 bg-slate-900/20 p-8 hover:border-indigo-500/20 transition-all duration-300 backdrop-blur-sm flex flex-col justify-between min-h-[240px]">
            <div>
              <div className="h-8 w-8 rounded-lg bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400 mb-4 font-bold text-sm">
                04
              </div>
              <h3 className="text-lg font-medium text-slate-200 group-hover:text-emerald-300 transition-colors font-sans">
                Persistent System File Tracking
              </h3>
              <p className="text-sm text-slate-400 mt-2 max-w-lg">
                Never lose progress across server restarts. Every generation
                variant, user message, and virtual sandbox file update saves
                continuously back to the cloud database layer.
              </p>
            </div>
            <span className="text-xs font-mono text-slate-600 mt-4">
              Automated Cloud State Backups
            </span>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="mt-20 border-t border-slate-900 py-8 text-center text-xs text-slate-500 font-mono">
        &copy; {new Date().getFullYear()} Dev Thread Systems Inc. All project
        code sandboxes open-sourced.
      </footer>

      {/* Inline blinking animation for custom caret */}
      <style>{`
        @keyframes blink {
          50% { background-color: transparent; }
        }
      `}</style>
    </div>
  );
};

export default Home;
